name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for notifying us about this bug! If the bug is a security
        vulnerabilty, please report it to xz@tukaani.org or create a private
        Security Advisory instead.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Also tell us, what did you expect to happen?
      placeholder: What happened
    validations:
      required: true
  - type: input
    id: our_version
    attributes:
      label: Version
      description: What version of our software are you running?
    validations:
      required: true
  - type: input
    id: os_version
    attributes:
      label: Operating System
      description: What OS type and version are you running?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
          Please copy and paste any relevant log output. This will be
          automatically formatted into code, so no need for backticks.
      render: shell
