name: Feature Request
description: Request a new feature
title: "[Feature Request]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion for a new feature!
  - type: textarea
    id: description
    attributes:
      label: Describe the Feature
      description: What should this new feature do?
      placeholder: Feature description here
    validations:
      required: true
  - type: textarea
    id: complications
    attributes:
      label: Expected Complications
      description: Do you expect any complications to this feature? Backwards compatibility or API/ABI breakage?
    validations:
      required: false
  - type: dropdown
    id: logs
    attributes:
      label: Will I try to implement this new feature?
      description: Let us know if you are planning on implementing this yourself or if you would like us to.
      options:
        - "Yes"
        - "No"
    validations:
      required: true
